### ISSUE TITLE
Battery interface directly on child devices

### ISSUE THREAD

**Issue by gsmart-pl** [gsmart-pl/Netatmo-QA-FIBARO-HC3#3]
What do you think, could you prepare a code that is not create a separate devices for showing battery levels and add this information (interface) to every battery operated device in parallel with main values (temperature, humidity, wind, rain, etc...)? I mean that these information should be directly at: outdoor devices additional indoor devices, wind and rain devices. I think that will be better than create separate devices only for battery levels...

Can I ask you for that? :)

**Comment by cdriget** [comment]
I personally prefer having a separate child device for each physical battery operated device, so that I can hide it in the Fibaro interface (both web and mobile), then it is collected only once by my monitoring tool.

But it may not be the case for everybody, so OK, I will add an option so the user can choose between the 2 options : either a dedicated battery device, or the battery information in every battery operated child devices.

**Comment by cdriget** [comment]
I made a new version 2.4 including the proposed change.
User may choose between the 2 options by setting the "battery_alone" quickapp variable to either "true" or "false".

**Comment by gsmart-pl** [comment]
That's cool but I've tried it in my environment and didn't get a "battery" interface on devices ;( I've wrote you a code review where, I think, is a small bug...

**Comment by cdriget** [comment]
You are right, sorry about that, insufficient testing.
It should be OK now.

**Comment by gsmart-pl** [comment]
Now everything works well :) So I merged changes and put updated version on marketplace.fibaro.com. It should be available tommorow. Now it is in review.
